---
# vars/main.yml

file_to_rm:
  - .bash_profile
  - .bashrc
  - .config/fish/

path_to_mk:
  - .config/alacritty/
  - .config/fish/conf.d/
  - .config/fish/functions/
  - .gnupg/
  - .local/bin/
  - .local/share/fonts/Hack/
  - .tmux/

my_std_xdg_path:
    - Pictures/Paste
    - Pictures/Screenshots
    - Pictures/Wallpapers
    - Videos/Screencasts

nord_alatty_url: https://raw.githubusercontent.com/arcticicestudio/nord-alacritty/develop/src/nord.yml

font_url: https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/patched-fonts/Hack/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete.ttf

wallpapers:
  - url: https://r4.wallpaperbetter.com/wallpaper/912/256/892/landscape-forest-deer-artwork-wallpaper-19d0082d01fa2debd647a8df70a166fd.jpg
    name: nord00.jpg
  - url: https://r4.wallpaperbetter.com/wallpaper/208/967/794/lake-artwork-gradient-vector-wallpaper-68665d38c080fca8809ca18e8862342a.jpg
    name: nord01.jpg
