import = ["/home/rox/.config/alacritty/nord.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "DejaVu Sans Mono"

[[keyboard.bindings]]
action = "Last"
key = "End"
mode = "Vi"

[window]
opacity = 0.91

[window.padding]
x = 19
y = 19
