---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "pip"
    directory: "/ansible/.ansible/dwm"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
