---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "07:00"
      timezone: "Europe/Rome"
    reviewers:
      - "andros21"
  - package-ecosystem: "pip"
    directory: "ansible/.ansible/dwm/requirements/ansible"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "07:00"
      timezone: "Europe/Rome"
    reviewers:
      - "andros21"
    groups:
      ansible:
        patterns:
          - "*"
        update-types:
          - "patch"
  - package-ecosystem: "pip"
    directory: "ansible/.ansible/dwm/requirements/pip"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "07:00"
      timezone: "Europe/Rome"
    reviewers:
      - "andros21"
    groups:
      pip:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pip"
    directory: "ansible/.ansible/dwm/roles/pkg/requirements"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "07:00"
      timezone: "Europe/Rome"
    reviewers:
      - "andros21"
    groups:
      local:
        patterns:
          - "*"
        exclude-patterns:
          - "yt-dlp"   # no semver
        update-types:
          - "minor"
          - "patch"
