---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "07:00"
      timezone: "Europe/Rome"
  - package-ecosystem: "pip"
    directory: "ansible/.ansible/dwm/requirements/ansible"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "07:00"
      timezone: "Europe/Rome"
    ignore:
      - dependency-name: "ansible-core"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    groups:
      ansible:
        patterns:
          - "*"
        exclude-patterns:
          - "ansible-lint"   # no semver
        update-types:
          - "patch"
  - package-ecosystem: "pip"
    directory: "ansible/.ansible/dwm/requirements/pip"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "07:00"
      timezone: "Europe/Rome"
    groups:
      pip:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pip"
    directory: "ansible/.ansible/dwm/roles/pkg/requirements"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "07:00"
      timezone: "Europe/Rome"
    groups:
      local:
        patterns:
          - "*"
        exclude-patterns:
          - "yt-dlp"   # no semver
        update-types:
          - "minor"
          - "patch"
