---
# tasks/fedora.yml

- name: Import rpmfusion free key
  ansible.builtin.rpm_key:
    key: '{{ repo_rpmfusion_free_key }}'
    state: present

- name: Add rpmfusion_free repos
  ansible.builtin.dnf:
    name: '{{ repo_rpmfusion }}'
    state: present
