# tasks/main.yml

- name: Import rpmfusion free key
  ansible.builtin.rpm_key:
    key: '{{ rpmfusion_free_key }}'
    state: present
  become: yes

- name: Add rpmfusion_free repos
  ansible.builtin.dnf:
    name: '{{ rpmfusion_repo }}'
    state: present
  become: yes

- name: Add flathub repo
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: '{{ flathub_repo }}'
    method: user
