---
# tasks/latest.yml

- name: Checkout latest tag for cloned gits
  ansible.builtin.shell:
    chdir: '{{ ansible_user_dir }}/Documents/dev/clone/{{ item | basename }}'
    cmd: |
      git fetch --tags
      latestTag=$(git tag --sort=-v:refname | grep -E -v '(-alpha|-beta|-rc|\.dev|\.pre)' | head -n1)
      git checkout $latestTag
  with_items: "{{ git_cloned_gits | map(attribute='origin') | list | select('match', '^.*com/.*/(?!(ytdl-mpv|teiler)).*') | list }}"
