---
# tasks/main.yml

- name: Clone forked gits
  ansible.builtin.git:
    repo: '{{ item.origin }}'
    dest: '{{ ansible_user_dir }}/Documents/dev/fork/{{ item.origin | basename }}'
    version: master
  with_items: '{{ forked_gits }}'

- name: Add upstream to forked gits
  ansible.builtin.shell:
    cmd: git remote add upstream '{{ item.upstream | quote }}'
    chdir: '{{ ansible_user_dir }}/Documents/dev/fork/{{ item.origin | basename }}'
  with_items: '{{ forked_gits }}'

- name: Clone cloned gits
  block:
    - name: Git clone others
      ansible.builtin.git:
        repo: '{{ item.origin }}'
        dest: '{{ ansible_user_dir }}/Documents/dev/clone/{{ item.origin | basename }}'
        version: '{{ item.branch }}'
      with_items: '{{ cloned_gits }}'
      when: item.origin | basename != 'ytdl-mpv'
    - name: Git clone ytdl-mpv
      ansible.builtin.git:
        repo: '{{ item.origin }}'
        dest: '{{ ansible_user_dir }}/Documents/dev/{{ item.origin | basename }}'
        version: '{{ item.branch }}'
      with_items: '{{ cloned_gits }}'
      when: item.origin | basename == 'ytdl-mpv'

- name: Clone ranger gits
  ansible.builtin.git:
    repo: '{{ item }}'
    dest: '{{ ansible_user_dir }}/.config/ranger/plugins/{{ item | basename }}'
    version: main
  with_items: '{{ ranger_gits }}'

- name: Latest tag
  ansible.builtin.include_tasks:
    file: latest.yml
