# tasks/main.yml

- name: "Clone forked gits"
  git:
    repo: "{{ item.origin }}"
    dest: "{{ ansible_user_dir }}/Documents/{{ item.origin | basename }}"
  with_items: "{{ forked_gits }}"

- name: "Add remote to forked gits"
  shell:
    cmd: git remote add remote "{{ item.remote | quote }}"
    chdir: "{{ ansible_user_dir }}/Documents/{{ item.origin | basename }}"
  with_items: "{{ forked_gits }}"

- name: "Clone cloned gits"
  git:
    repo: "{{ item }}"
    dest: "{{ ansible_user_dir }}/Documents/{{ item | basename }}"
  with_items: "{{ cloned_gits }}"

- name: "Devel branch on cloned gits"
  shell:
    cmd: git checkout -b devel
    chdir: "{{ ansible_user_dir }}/Documents/{{ item | basename }}"
  with_items: "{{ cloned_gits }}"

- name: "Clone ranger gits"
  git:
    repo: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.config/ranger/plugins/{{ item | basename }}"
  with_items: "{{ ranger_gits }}"
