alias l    'll'
alias rm   'rm -i'
alias md   'mkdir -p'
alias p    'cd -'
alias ..   'cd ..'
alias ...  'cd ../..'
alias gpg  'gpg2'
alias nv   'nvim'
alias gmm  'fish_gio_mount'
alias gmu  'fish_gio_umount'
alias less 'bat'
alias cat  'bat'
