---
# tasks/alpine.yml

- name: Update pkgs
  community.general.apk:
    upgrade: yes
    update_cache: yes

- name: Add needed pkgs
  block:
    - name: Apk add
      community.general.apk:
        name: '{{ pkg_base + pkg_base_deps + pkg_base_libs + pkg_build + pkg_utils }}'
        state: present
        update_cache: yes
    - name: Setup base xorg
      ansible.builtin.command:
        cmd: setup-xorg-base
    - name: Apk add plus
      community.general.apk:
        name: '{{ pkg_audio_deps + pkg_input_deps + pkg_net_deps + pkg_uefi_bios_deps + pkg_video_deps + pkg_xorg_deps }}'
        state: present
        update_cache: yes
    - name: Apk add edge/community
      community.general.apk:
        name: '{{ pkg_edge_community }}'
        state: present
        update_cache: yes
        repository: '{{ pkg_edge_community_repo }}'
    - name: Apk add edge/testing
      community.general.apk:
        name: '{{ pkg_edge_testing }}'
        state: present
        update_cache: yes
        repository: '{{ pkg_edge_testing_repo }}'
