---
# tasks/common.yml

- name: Add user needed pkgs
  block:
    - name: Flatpak install
      community.general.flatpak:
        name: '{{ item }}'
        state: present
        method: user
      with_items: '{{ flathub }}'
    - name: Pip install
      ansible.builtin.pip:
        name: '{{ item }}'
        state: present
        executable: /usr/bin/pip
        extra_args: --user
      with_items: '{{ pypi }}'
