---
# tasks/common.yml

- name: Add user needed pkgs
  block:
    - name: Flatpak install
      community.general.flatpak:
        name: '{{ item }}'
        state: present
        method: user
      with_items: '{{ pkg_flathub }}'
    - name: Setup venv local
      ansible.builtin.pip:
        chdir: '{{ playbook_dir }}'
        requirements: requirements/pip/pip.txt
        virtualenv_command: python3 -m venv
        virtualenv: '{{ pkg_venv }}/local'
    - name: Pip install
      ansible.builtin.command:
        cmd: |
          {{ pkg_venv }}/local/bin/python3 -m pip install --upgrade -r {{ role_path }}/requirements/local.in -c {{ role_path }}/requirements/local.txt
