---
# tasks/common.yml

- name: Add user needed pkgs
  block:
    - name: Flatpak install
      community.general.flatpak:
        name: '{{ item }}'
        state: present
        method: user
      with_items: '{{ pkg_flathub }}'
    - name: Setup venv local
      ansible.builtin.pip:
        chdir: '{{ playbook_dir }}'
        requirements: requirements/pip-tools/pip-tools.txt
        virtualenv_command: python3 -m venv
        virtualenv: '{{ pkg_venv }}/local'
    - name: Piptools sync
      ansible.builtin.command:
        cmd: |
          {{ pkg_venv }}/local/bin/python3 -m piptools sync requirements/pip-tools/pip-tools.txt {{ role_path }}/requirements/local.txt
