---
# tasks/fedora.yml

- name: Update pkgs
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_cache: yes

- name: Add needed pkgs
  block:
    - name: Dnf install
      ansible.builtin.dnf:
        name: '{{ pkg_base + pkg_base_deps + pkg_base_libs + pkg_build + pkg_utils + pkg_drivers }}'
        state: present
        update_cache: yes
    - name: Dnf remove
      ansible.builtin.dnf:
        name: firefox
        state: absent
