# tasks/main.yml

- name: Update pkgs
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_cache: yes
  become: yes

- name: Add needed pkgs
  block:
    - name: Dnf install
      ansible.builtin.dnf:
        name: '{{ base + base_deps + base_libs + build + utils }}'
        state: present
        update_cache: yes
      become: yes
    - name: Flatpak install
      community.general.flatpak:
        name: '{{ item }}'
        state: present
        method: user
      with_items: '{{ flathub }}'
    - name: Pip install
      ansible.builtin.pip:
        name: '{{ item }}'
        state: present
      with_items: '{{ pypi }}'

- name: Download and install pyenv
  block:
    - name: Download pyenv
      ansible.builtin.get_url:
        url: https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer
        dest: /tmp/pyenv-installer
    - name: Install pyenv
      ansible.builtin.command: bash /tmp/pyenv-installer

- name: Create py3nvim env
  ansible.builtin.shell: |
    ~/.pyenv/bin/pyenv virtualenv py3nvim
    ~/.pyenv/versions/py3nvim/bin/pip install pynvim
    exit 0
