---
- name: Update
  hosts: laptop
  tasks:
    - name: Dnf update
      tags: pkg
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_cache: yes
      become: yes
      when: ansible_distribution == "Fedora"
    - name: Apk update
      tags: pkg
      community.general.apk:
        upgrade: yes
        update_cache: yes
      become: yes
      when: ansible_distribution == "Alpine"
    - name: Cloned git update
      tags: git
      block:
        - name: Include git from latest
          ansible.builtin.include_role:
            name: git
            tasks_from: latest
        - name: Include build from latest
          ansible.builtin.include_role:
            name: build
            tasks_from: latest
    - name: Flatpak update
      tags: flatpak
      ansible.builtin.command:
        cmd: |
          flatpak --user update --assumeyes --noninteractive
    - name: Pip update
      tags: pip
      block:
        - name: Piptools sync
          ansible.builtin.command:
            cmd: |
              {{ pkg_venv }}/local/bin/python3 -m piptools sync requirements/pip-tools/pip-tools.txt roles/pkg/requirements/local.txt
          vars:
            pkg_venv: '{{ ansible_user_dir }}/.local/share/venv/py{{ ansible_python.version.major }}{{ ansible_python.version.minor }}'
