---
- name: Update
  hosts: laptop
  tasks:
    - name: Dnf update
      tags: pkg
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_cache: yes
      become: yes
      when: ansible_distribution == "Fedora"
    - name: Apk update
      tags: pkg
      community.general.apk:
        upgrade: yes
        update_cache: yes
      become: yes
      when: ansible_distribution == "Alpine"
    - name: Cloned git update
      tags: git
      block:
        - name: Include git from latest
          ansible.builtin.include_role:
            name: git
            tasks_from: latest
        - name: Include build from latest
          ansible.builtin.include_role:
            name: build
            tasks_from: latest
    - name: Flatpak update
      tags: flatpak
      ansible.builtin.command:
        cmd: |
          flatpak --user update --assumeyes --noninteractive
    - name: Pip update
      tags: pip
      block:
        - name: Pip upgrade
          ansible.builtin.shell:
            cmd: |
              {{ pkg_py }} -m pip install --upgrade -r requirements/pip/pip.in -c requirements/pip/pip.txt
              {{ pkg_py }} -m pip install --upgrade -r roles/pkg/requirements/local.in -c roles/pkg/requirements/local.txt
          vars:
            pkg_py: '{{ ansible_user_dir }}/.local/share/venv/py{{ ansible_python.version.major }}{{ ansible_python.version.minor }}/local/bin/python3'
