---
- hosts: debians
  serial: 1
  tasks:
    - name: apt update
      ansible.builtin.apt:
        upgrade: 'yes'
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
      register: apt_updates

- hosts: redhats
  tasks:
    - name: dnf update
      dnf:
        name: '*'
        state: latest
        update_cache: yes
      register: dnf_updates
