---
- hosts: debians
  tasks:
    - name: apt update
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: apt upgrade
      apt: upgrade=yes force_apt_get=yes

- hosts: redhats
  tasks:
    - name: dnf update
      dnf: update_cache=yes state=latest name=*
