---
- hosts: debians
  serial: 1
  tasks:
    - name: apt update
      ansible.builtin.apt:
        upgrade: 'yes'
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

- hosts: redhats
  tasks:
    - name: dnf update
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_cache: yes

- hosts: all:!raspis
  tasks:
    - name: last kernel
      ansible.builtin.shell:
        cmd: ls -tr /boot/ | egrep "^vmlinuz-[3-9]" | tail -1 | cut -d'-' -f2-
      register: last_kernel
    - name: check reboot
      debug:
        msg: "New kernel installed. Reboot when possible!"
      when: "ansible_kernel != last_kernel.stdout"
