---
# tasks/common.yml

- name: Setup XDG standard dirs
  ansible.builtin.command:
    cmd: xdg-user-dirs-update

- name: GNU/Stow
  block:
    - name: Remove default configs
      ansible.builtin.file:
        path: '{{ ansible_user_dir }}/{{ item }}'
        state: absent
      with_items: '{{ conf_file_to_rm }}'
    - name: Create some locations
      ansible.builtin.file:
        path: '{{ ansible_user_dir }}/{{ item }}'
        state: directory
      with_items: '{{ conf_path_to_mk }}'
    - name: Collect paths to stow
      ansible.builtin.find:
        paths: '{{ ansible_user_dir }}/.dotfiles/'
        file_type: directory
        excludes: .cache,.git,.github,Xorg
      register: conf_find_result
    - name: Stow them
      ansible.builtin.command:
        cmd: stow "{{ item.path | basename }}"
        chdir: '{{ ansible_user_dir }}/.dotfiles/'
      with_items: '{{ conf_find_result.files }}'

- name: Create not standard XDG dirs
  ansible.builtin.file:
    path: '{{ ansible_user_dir }}/{{ item }}'
    state: directory
  with_items: '{{ conf_my_std_xdg_path }}'

- name: Syncthing .stignore
  block:
    - name: In dev
      ansible.builtin.copy:
        dest: '{{ ansible_user_dir }}/Documents/dev/.stignore'
        content: |
          // .stignore
          //
          #include ../../.config/git/ignore
          clone/
          fork/
          **/build/
          **/target/
    - name: In gnupg
      ansible.builtin.copy:
        dest: '{{ ansible_user_dir }}/.gnupg/.stignore'
        content: |
          // .stignore
          //
          #include ../.config/git/ignore
          random_seed
          .#*

- name: Download nord theme alacritty
  block:
    - name: Download nord theme
      ansible.builtin.get_url:
        url: '{{ conf_nord_alatty_url }}'
        dest: '{{ ansible_user_dir }}/.config/alacritty/nord.yml'
    - name: Temp patch it (lazy upstream)
      ansible.builtin.replace:
        path: '{{ ansible_user_dir }}/.config/alacritty/nord.yml'
        regexp: 'bar:'
        replace: 'footer_bar:'

- name: Download and install Hack Nerd Fonts
  block:
    - name: Download Hack Nerd Fonts
      ansible.builtin.get_url:
        url: '{{ conf_font_url }}'
        dest: '/tmp/Hack.tar.xz'
    - name: Extract Hack Nerd Fonts
      ansible.builtin.unarchive:
        src: '/tmp/Hack.tar.xz'
        dest: '{{ ansible_user_dir }}/.local/share/fonts/Hack/'
    - name: Install Hack Nerd Fonts
      ansible.builtin.command: fc-cache -f

- name: Download and set wallpaper
  ansible.builtin.get_url:
    url: '{{ item.url }}'
    dest: '{{ ansible_user_dir }}/Pictures/Wallpapers/{{ item.name }}'
  with_items: '{{ conf_wallpapers }}'
