---
# tasks/fedora.yml

- name: Xorg conf
  block:
    - name: Create dir conf
      ansible.builtin.file:
        path: '{{ conf_xorg.dest | dirname }}'
        state: directory
    - name: Copy conf from template
      ansible.builtin.template:
        src: '{{ conf_xorg.src }}'
        dest: '{{ conf_xorg.dest }}'
        owner: root
        group: root
        mode: 0644

- name: Firewalld conf
  ansible.builtin.command: firewall-cmd --set-default-zone=drop

- name: Chsh fish
  ansible.builtin.user:
    name: '{{ ansible_user_id }}'
    shell: /usr/bin/fish
