---
# tasks/main.yml

- name: Fedora
  block:
    - ansible.builtin.include_tasks:
        file: fedora.yml
  become: yes
  when: ansible_distribution == "Fedora"

- name: Alpine Linux
  block:
    - ansible.builtin.include_vars:
        file: alpine.yml
    - ansible.builtin.include_tasks:
        file: alpine.yml
  become: yes
  when: ansible_distribution == "Alpine"

- name: Common
  ansible.builtin.include_tasks:
    file: common.yml
