---
# tasks/main.yml

- name: Xorg conf
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    mode: 0644
  become: true
  with_items: '{{ Xorg }}'

- name: Change dwm path
  vars:
    my_user_home: '{{ ansible_user_dir }}'
  ansible.builtin.replace:
    ansible.builtin.path: '{{ Xorg[0].dest }}'
    regexp: Exec=*
    ansible.builtin.replace: Exec={{ my_user_home }}/.local/bin/dwm
  become: true

- name: Firewalld conf
  ansible.builtin.command: firewall-cmd --set-default-zone=drop
  become: true

- name: Disable systemd-resolved
  block:
    - name: Disable systemd-resolved
      ansible.builtin.service:
        name: systemd-resolved
        state: stopped
        enabled: no
    - name: Remove /etc/resolv.conf
      ansible.builtin.file:
        path: /etc/resolv.conf
        state: absent
    - name: Restart NetworkManager
      ansible.builtin.service:
        name: NetworkManager
        state: restarted
  become: true

- name: Download and install pyenv
  block:
    - name: Download pyenv
      ansible.builtin.get_url:
        url: https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer
        dest: /tmp/pyenv-installer
    - name: Install pyenv
      ansible.builtin.command: bash /tmp/pyenv-installer

- name: Create py3nvim env
  ansible.builtin.shell: |
    ~/.pyenv/bin/pyenv virtualenv py3nvim
    ~/.pyenv/versions/py3nvim/bin/pip install pynvim
    exit 0

- name: GNU/Stow
  block:
    - name: Remove default configs
      ansible.builtin.file:
        ansible.builtin.path: '{{ ansible_user_dir }}/{{ item }}'
        state: absent
      with_items: '{{ file_to_rm }}'
    - name: Create some locations
      ansible.builtin.file:
        ansible.builtin.path: '{{ ansible_user_dir }}/{{ item }}'
        state: directory
      with_items: '{{ path_to_mk }}'
    - name: Collect paths to stow
      ansible.builtin.find:
        paths: '{{ ansible_user_dir }}/.dotfiles/'
        file_type: directory
        excludes: .git,Xorg
      register: find_result
    - name: Stow them
      ansible.builtin.shell:
        cmd: stow "{{ item.path | basename }}"
        chdir: '{{ ansible_user_dir }}/.dotfiles/'
      with_items: '{{ find_result.files }}'

- name: Chsh fish
  ansible.builtin.user:
    name: '{{ ansible_user_id }}'
    ansible.builtin.shell: /usr/bin/fish
  become: true

- name: Patch cloned gits
  ansible.builtin.patch:
    src: '{{ item }}'
    dest: '{{ ansible_user_dir }}/Documents/{{ item[:-8] | basename }}/Makefile'
  with_items: "{{ lookup('fileglob', '{{ playbook_dir }}/roles/conf/patches/cloned_gits/*.diff', wantlist=True) }}"

- name: Create (my) standard xdg paths
  file:
    ansible.builtin.path: '{{ ansible_user_dir }}/{{ item }}'
    state: directory
  with_items: '{{ my_std_xdg_path }}'

- name: Download nord theme alacritty
  ansible.builtin.get_url:
    url: '{{ nord_alatty_url }}'
    dest: '{{ ansible_user_dir }}/.config/alacritty/nord.yml'

- name: Download and install Hack Nerd Fonts
  block:
    - name: Download Hack Nerd Fonts
      ansible.builtin.get_url:
        url: '{{ font_url }}'
        dest: '{{ ansible_user_dir }}/.local/share/fonts/Hack/'
    - name: Install Hack Nerd Fonts (2/2)
      ansible.builtin.command: fc-cache -f

- name: Download default wallpaper
  ansible.builtin.get_url:
    url: '{{ wallpaper_url }}'
    dest: '{{ ansible_user_dir }}/Pictures/Wallpapers/nord.jpg'
