---
name: Lint CI

"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  changes:
    name: Filter changes
    runs-on: ubuntu-latest
    outputs:
      scripts: ${{ steps.filter.outputs.scripts }}
      playbooks: ${{ steps.filter.outputs.playbooks }}
    steps:
      - name: checkout project
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: filter
        with:
          filters: |
            scripts:
              - '**/.local/bin/*'
            playbooks:
              - 'ansible/.ansible/**'
  lint-shell:
    name: Lint scripts
    needs: changes
    if: ${{ needs.changes.outputs.scripts == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
      - name: Shellcheck scripts
        run: |
          find -- * -type f -executable -exec shellcheck {} \;
  lint-playbook:
    name: Lint playbooks
    needs: changes
    if: ${{ needs.changes.outputs.playbooks == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
      - name: Setup env
        run: |
          python -m venv "$HOME/.venv"
          { echo "HOME=$HOME";
            echo "PATH=$HOME/.venv/bin:$PATH";
            echo "ansible_dwm=ansible/.ansible/dwm/";
          } >> "$GITHUB_ENV"
      - name: Install requirements-dev.txt
        run: |
          cd "$ansible_dwm"
          python -m pip install --upgrade -r requirements/pip/pip.in -c requirements/pip/pip.txt
          python3 -m pip install --upgrade -r requirements/ansible/ansible-dev.in -c requirements/ansible/ansible-dev.txt
      - name: Check ansible version
        run: |
          ansible --version
          ansible-lint --version
      - name: Install requirements.yml
        run: |
          cd "$ansible_dwm"
          ansible-galaxy collection install -r requirements/ansible/requirements.yml
      - name: Run yaml-lint
        run: |
          cd "$ansible_dwm"
          yamllint .
      - name: Run playbook syntax-check
        run: |
          cd "$ansible_dwm"
          ansible-playbook --syntax-check playbooks/dwm.yml
          ansible-playbook --syntax-check playbooks/update.yml
      - name: Run ansible-lint
        run: |
          cd "$ansible_dwm"
          ansible-lint
