---
name: Lint CI

"on":
  push:
    branches:
      - master
    paths:
      - 'ansible/.ansible/**'
  pull_request:
    branches:
      - master
    paths:
      - 'ansible/.ansible/**'

permissions: read-all

jobs:
  lint:
    name: Lint playbooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Setup some envs
        run: |
          echo "HOME=$HOME" >> $GITHUB_ENV
          echo "PATH=$PATH:$HOME/.local/bin" >> $GITHUB_ENV
          echo "ansible_dwm=ansible/.ansible/dwm/" >> $GITHUB_ENV
      - name: Install requirements-dev.txt
        run: |
          cd $ansible_dwm
          python -m pip install -r requirements-dev.txt
      - name: Check ansible version
        run: |
          ansible --version
          ansible-lint --version
      - name: Install requirements.yml
        run: |
          cd $ansible_dwm
          ansible-galaxy collection install -r requirements.yml
      - name: Run yaml-lint
        run: |
          cd $ansible_dwm
          yamllint .
      - name: Run playbook syntax-check
        run: |
          cd $ansible_dwm
          ansible-playbook --syntax-check dwm.yml
          ansible-playbook --syntax-check update.yml
      - name: Run ansible-lint
        run: |
          cd $ansible_dwm
          ansible-lint dwm.yml
          ansible-lint update.yml
