---
name: Lint CI

"on":
  push:
    branches:
      - master
    paths:
      - 'ansible/.ansible/**'
  pull_request:
    branches:
      - master
    paths:
      - 'ansible/.ansible/**'

permissions:
  contents: read

jobs:
  lint:
    name: Lint playbooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Setup some envs
        run: |
          echo "HOME=$HOME" >> $GITHUB_ENV
          echo "PATH=$PATH:$HOME/.local/bin" >> $GITHUB_ENV
          echo "ansible_dwm=ansible/.ansible/dwm/" >> $GITHUB_ENV
      - name: Check requirements-dev.txt cache
        uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77
        id: cache-txt
        with:
          path: |
            ~/.local/bin
            ~/.local/lib
          key: |
            ${{ runner.os }}-ansible-${{ hashFiles('**/requirements-dev.txt') }}
      - name: Install requirements-dev.txt
        if: steps.cache-txt.outputs.cache-hit != 'true'
        run: |
          cd $ansible_dwm
          python -m pip install -r requirements-dev.txt
      - name: Check ansible version
        run: |
          ansible --version
          ansible-lint --version
      - name: Check requirements.yml cache
        uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77
        id: cache-yml
        with:
          path: |
            ~/.ansible/collections
          key: |
            ${{ runner.os }}-ansible-${{ hashFiles('**/requirements.yml') }}
      - name: Install requirements.yml
        if: steps.cache-yml.outputs.cache-hit != 'true'
        run: |
          cd $ansible_dwm
          ansible-galaxy collection install -r requirements.yml
      - name: Run yaml-lint
        run: |
          cd $ansible_dwm
          yamllint .
      - name: Run playbook syntax-check
        run: |
          cd $ansible_dwm
          ansible-playbook --syntax-check dwm.yml
          ansible-playbook --syntax-check update.yml
      - name: Run ansible-lint
        run: |
          cd $ansible_dwm
          ansible-lint --offline dwm.yml
          ansible-lint --offline update.yml
